### ISSUE TITLE
Compiling fails at compile prores encoder

### ISSUE THREAD

**Issue by ambustion** [UDaManFunks/prores_encoder#1]
I believe the step under compile prores encoder is missing some information. The line "2) Inside the command prompt, type "cd /d C:\VideoEditingUtils\x265_plugin_build\prores_encoder" looks to be the wrong folder path and running nmake can't see ffmpeg from this directory.

**Comment by UDaManFunks** [comment]
I corrected it, it should be


  *   Inside the command prompt, type "cd /d C:\VideoEditingUtils\prores_plugin_build\prores_encoder"



Sent from Outlook<http://aka.ms/weboutlook>

________________________________
From: ambustion ***@***.***>
Sent: Monday, July 29, 2024 1:04 AM
To: UDaManFunks/prores_encoder ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [UDaManFunks/prores_encoder] Compiling fails at compile prores encoder (Issue #1)


I believe the step under compile prores encoder is missing some information. The line "2) Inside the command prompt, type "cd /d C:\VideoEditingUtils\x265_plugin_build\prores_encoder" looks to be the wrong folder path and running nmake can't see ffmpeg from this directory.

**Comment by ambustion** [comment]
Thank you. I'm getting the error 
```
plugin.cpp
C:\VideoEditingUtils\prores_plugin_build\prores_encoder\profilemap.h(6): fatal error C1083: Cannot open include file: 'libavutil/avutil.h': No such file or directory
NMAKE : fatal error U1077: 'cl -Iinclude -I../ffmpeg_pkg/include /Fo:build/ /c /EHsc /std:c++20 /W3 /O2 plugin.cpp' : return code '0x2'
Stop.
```

and if I copy the ffmpeg folder into the include folder so it sees it easier I am then left with the error:
`LINK : fatal error LNK1181: cannot open input file '..\ffmpeg_pkg\lib\libavcodec.a'
NMAKE : fatal error U1077: 'link /DLL wrapper/build/*.obj build/*.obj ../ffmpeg_pkg/lib/libavcodec.a ../ffmpeg_pkg/lib/libavfilter.a  ../ffmpeg_pkg/lib/libswscale.a ../ffmpeg_pkg/lib/libswresample.a ../ffmpeg_pkg/lib/libavutil.a /OUT:bin/prores_encoder.dvcp' : return code '0x49d'
Stop.`

Appreciate any guidance.

**Comment by ambustion** [comment]
I keep getting stuck with this error at the step of compiling the prores encoder.  I don't have this directory though. Am I missing a step.
```

LINK : fatal error LNK1181: cannot open input file '..\ffmpeg_pkg\lib\libavcodec.a'
NMAKE : fatal error U1077: 'link /DLL wrapper/build/*.obj build/*.obj ../ffmpeg_pkg/lib/libavcodec.a ../ffmpeg_pkg/lib/libavfilter.a  ../ffmpeg_pkg/lib/libswscale.a ../ffmpeg_pkg/lib/libswresample.a ../ffmpeg_pkg/lib/libavutil.a /OUT:bin/prores_encoder.dvcp' : return code '0x49d'
Stop.
```

**Comment by UDaManFunks** [comment]
There's a step missing, after

"make V=1 -j 8"

do a 

"make install"

it should create the ffmpeg_pkg folder and copy the binaries there.

**Comment by ambustion** [comment]
Amazing thank you. This all works and it compiles. Resolve is not seeing it yet but I will troubleshoot further. Edit. Just started completely over and ran through it all fresh and it is picked up by resolve. Thank you so much!
